language: go
go:
  - 1.13.x
  - 1.14.x
before_install:
  - sudo apt update
  - sudo apt install libasound2 libasound2-dev
  - go get github.com/hajimehoshi/oto
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -package=github.com/tosone/minimp3
